namespace MECS.Core
{
    //* Static class used to store default naming of Scriptable objects generated by framework
    public static class MECSDefaultSettingsNaming
    {
        //Variables
        //Default general paths used
        public static readonly string DEFAULT_SETTINGS_PATH = "Assets/Resources/MECS",
        DEFAULT_SETTINGS_PARENT_PATH = "Assets/Resources",
        DEFAULT_SETTINGS_FOLDER_NAME = "MECS",
        DEFAULT_SETTINGS_SHORT_PATH = "MECS";

        //Instances of naming
        public static readonly SystemsNaming systemsNaming = new();
        public static readonly ManagersNaming managersNaming = new();
        public static readonly ScriptableObjectsNaming scriptableObjectsNaming = new();
        public static readonly InputScriptableObjectsNaming inputScriptableObjectsNaming = new();

        //Nested class used to store systems information
        public class SystemsNaming
        {
            //Variables
            public readonly string DEFAULT_SYSTEMS_PATH = "Assets/Resources/MECS/Systems",
            DEFAULT_SYSTEMS_FOLDER_NAME = "Systems",
            DEFAULT_SYSTEMS_SHORT_PATH = "MECS/Systems";
            public readonly SystemAssetsNaming systemAssetsNaming = new();

            //Nested class, store system assets naming
            public class SystemAssetsNaming
            {
                //Variables
                public readonly string COLLIDER_SYSTEM_NAME = "Collider_System",
                    CONDITIONAL_SYSTEM_NAME = "Conditional_System",
                    SCRIPTABLE_ENUM_SYSTEM_NAME = "Scriptable_Enum_System",
                    EVENT_SYSTEM_NAME = "Event_System",
                    FILTER_SYSTEM_NAME = "Filter_System",
                    GAME_EVENT_LISTENER_SYSTEM_NAME = "Game_Event_Listener_System",
                    INPUT_SYSTEM_NAME = "Input_System",
                    LIFE_CYCLE_SYSTEM_NAME = "Life_Cycle_System",
                    ADDRESABLE_ENTITY_SYSTEM_NAME = "Addresable_Entity_System",
                    ADDRESABLE_POOLED_SYSTEM_NAME = "Addresable_Pooled_System",
                    CASTING_SYSTEM_NAME = "Casting_System",
                    TIMER_SYSTEM_NAME = "Timer_System";
            }
        }

        //Nested class used to store managers information
        public class ManagersNaming
        {
            //Variables
            public readonly string DEFAULT_MANAGERS_PATH = "Assets/Resources/MECS/Managers",
            DEFAULT_MANAGERS_FOLDER_NAME = "Managers",
            DEFAULT_MANAGERS_SHORT_PATH = "MECS/Managers";
            public readonly ManagersAssetsNaming managersAssetsNaming = new();

            //Nested class, store managers assets naming
            public class ManagersAssetsNaming
            {
                //Variables
                public readonly string COLLIDER_MANAGER_NAME = "Collider_Manager",
                    CONDITIONAL_MANAGER_NAME = "Conditional_Manager",
                    SCRIPTABLE_ENUM_MANAGER_NAME = "Scriptable_Enum_Manager",
                    EVENT_MANAGER_NAME = "Event_Manager",
                    FILTER_MANAGER_NAME = "Filter_Manager",
                    GAME_EVENT_LISTENER_MANAGER_NAME = "Game_Event_Listener_Manager",
                    LIFE_CYCLE_MANAGER_NAME = "Life_Cycle_Manager",
                    ADDRESABLE_ENTITY_MANAGER_NAME = "Addresable_Entity_Manager",
                    ADDRESABLE_POOLED_MANAGER_NAME = "Addresable_Pooled_Manager",
                    CASTING_MANAGER_NAME = "Casting_Manager",
                    TIMER_MANAGER_NAME = "Timer_Manager",
                    EVENT_TRACKING_MANAGER_NAME = "Event_Tracking_Manager";
            }
        }

        //Nested class used to store scriptable objects information
        public class ScriptableObjectsNaming
        {
            //Variables
            public readonly string DEFAULT_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects",
            DEFAULT_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Scriptable_Objects",
            DEFAULT_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects";

            //Variables
            public readonly CastingScriptableObjectsNaming castingScriptableObjectsNaming = new();
            public readonly ConditionalsScriptableObjectsNaming conditionalsScriptableObjectsNaming = new();
            public readonly TimerScriptableObjectsNaming timerScriptableObjectsNaming = new();
            public readonly AddresablePooledScriptableObjectsNaming addresablePooledScriptableObjectsNaming = new();
            public readonly FunctionalitiesScriptableObjectsNaming functionalitiesScriptableObjectsNaming = new();
            public readonly GameEventListenerScriptableObjectsNaming gameEventListenerScriptableObjectsNaming = new();

            //Nested class, used to store scriptable object casting information
            public class CastingScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_CASTING_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects/Casting",
                DEFAULT_CASTING_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Casting",
                DEFAULT_CASTING_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects/Casting";
                public readonly CastingScriptableObjectsAssetsNaming castingScriptableObjectsAssetsNaming = new();

                //Nested class, store casting scriptable objects assets naming
                public class CastingScriptableObjectsAssetsNaming
                {
                    //Variables
                    public readonly string START_CASTING_STATE_COMMAND_NAME = "Start_Casting_State_Command",
                    STOP_CASTING_STATE_COMMAND_NAME = "Stop_Casting_State_Command";
                }
            }

            //Nested class, used to store scriptable object conditionals information
            public class ConditionalsScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_CONDITIONALS_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects/Conditionals",
                DEFAULT_CONDITIONALS_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Conditionals",
                DEFAULT_CONDITIONALS_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects/Conditionals";
                public readonly ConditionalsScriptableObjectsAssetsNaming conditionalsScriptableObjectsAssetsNaming = new();

                //Nested class, store conditionals scriptable objects assets naming
                public class ConditionalsScriptableObjectsAssetsNaming
                {
                    //Variables
                    public readonly string CHECK_CONDITIONALS_COMMAND_NAME = "Check_Conditionals_Command",
                    SET_FALSE_BOOLEAN_CONDITIONAL_COMMAND_NAME = "Set_False_Boolean_Conditional_Command",
                    SET_TRUE_BOOLEAN_CONDITIONAL_COMMAND_NAME = "Set_True_Boolean_Conditional_Command";
                }
            }

            //Nested class, used to store scriptable object timer information
            public class TimerScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_TIMER_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects/Timer",
                DEFAULT_TIMER_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Timer",
                DEFAULT_TIMER_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects/Timer";
                public readonly TimerScriptableObjectsAssetsNaming timerScriptableObjectsAssetsNaming = new();

                //Nested class, store timer scriptable objects assets naming
                public class TimerScriptableObjectsAssetsNaming
                {
                    //Variables
                    public readonly string INITIALIZE_TIMER_COMMAND_NAME = "Initialize_Timer_Command",
                    PAUSE_TIMER_COMMAND_NAME = "Pause_Timer_Command",
                    RUN_TIMER_COMMAND_NAME = "Run_Timer_Command",
                    STOP_TIMER_COMMAND_NAME = "Stop_Timer_Command";
                }
            }

            //Nested class, used to store scriptable object addresable pooled information
            public class AddresablePooledScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_ADDRESABLE_POOLED_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects/Addresable_Pooled",
                DEFAULT_ADDRESABLE_POOLED_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Addresable_Pooled",
                DEFAULT_ADDRESABLE_POOLED_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects/Addresable_Pooled";
                public readonly AddresablePooledScriptableObjectsAssetsNaming addresablePooledScriptableObjectsAssetsNaming = new();

                //Nested class, store addresable pooled scriptable objects assets naming
                public class AddresablePooledScriptableObjectsAssetsNaming
                {
                    //Variables
                    public readonly string INITIALIZE_POOL_COMMAND_NAME = "Initialize_Pool_Command",
                    RETURN_POOLED_ENTITY_COMMAND_NAME = "Return_Pooled_Entity_Command";
                }
            }

            //Nested class, used to store scriptable object functionalities information
            public class FunctionalitiesScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_FUNCTIONALITIES_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects/Functionalities",
                DEFAULT_FUNCTIONALITIES_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Functionalities",
                DEFAULT_FUNCTIONALITIES_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects/Functionalities";
                public readonly FunctionalitiesScriptableObjectsAssetsNaming functionalitiesScriptableObjectsAssetsNaming = new();

                //Nested class, store addresable pooled scriptable objects assets naming
                public class FunctionalitiesScriptableObjectsAssetsNaming
                {
                    //Variables
                    public readonly string DESTROY_ENTITY_COMMAND_NAME = "Destroy_Entity_Command";
                }
            }

            //Nested class, used to store scriptable object gameEventListener information
            public class GameEventListenerScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_GAME_EVENT_LISTENER_SCRIPTABLE_OBJECTS_PATH = "Assets/Resources/MECS/Scriptable_Objects/Game_Event",
                DEFAULT_GAME_EVENT_LISTENER_SCRIPTABLE_OBJECTS_FOLDER_NAME = "Game_Event",
                DEFAULT_GAME_EVENT_LISTENER_SCRIPTABLE_OBJECTS_SHORT_PATH = "MECS/Scriptable_Objects/Game_Event";
                public readonly GameEventListenerScriptableObjectsAssetsNaming gameEventListenerScriptableObjectsAssetsNaming = new();

                //Nested class, store addresable pooled scriptable objects assets naming
                public class GameEventListenerScriptableObjectsAssetsNaming
                {
                    //Variables
                    public readonly string GAME_EVENT_REGISTRATION_COMMAND_NAME = "Game_Event_Registration_Command",
                    GAME_EVENT_UNREGISTER_COMMAND_NAME = "Game_Event_Unregister_Command";
                }
            }
        }

        //Nested class used to store input scriptable objects information
        public class InputScriptableObjectsNaming
        {
            //Variables
            public readonly string DEFAULT_INPUT_PATH = "Assets/Resources/MECS/Input",
            DEFAULT_INPUT_FOLDER_NAME = "Input",
            DEFAULT_INPUT_SHORT_PATH = "MECS/Input";
            public readonly PCInputScriptableObjectsNaming pcInputScriptableObjectsNaming = new();

            //Nested class, used to store scriptable object pc input information
            public class PCInputScriptableObjectsNaming
            {
                //Variables
                public readonly string DEFAULT_PC_INPUT_PATH = "Assets/Resources/MECS/Input/PC",
                DEFAULT_PC_INPUT_FOLDER_NAME = "PC",
                DEFAULT_PC_INPUT_SHORT_PATH = "MECS/Input/PC";
                public readonly MouseInputScriptableObjectsNaming mouseInputScriptableObjectsNaming = new();
                public readonly KeyboardInputScriptableObjectsNaming keyboardInputScriptableObjectsNaming = new();

                //Nested class, used to store scriptable object mouse input information
                public class MouseInputScriptableObjectsNaming
                {
                    //Variables
                    public readonly string DEFAULT_MOUSE_INPUT_PATH = "Assets/Resources/MECS/Input/PC/Mouse",
                    DEFAULT_MOUSE_INPUT_FOLDER_NAME = "Mouse",
                    DEFAULT_MOUSE_INPUT_SHORT_PATH = "MECS/Input/PC/Mouse";
                    public readonly MouseInputAssetsScriptableObjectsNaming mouseInputAssetsScriptableObjectsNaming = new();

                    //Nested class, used to store scriptable object assets mouse input information
                    public class MouseInputAssetsScriptableObjectsNaming
                    {
                        //Variables
                        public readonly string LEFT_CLICK_BUTTON_PERFORMED_VARIABLE_NAME = "Left_Click_Button_Performed_Variable",
                        LEFT_CLICK_BUTTON_CANCELED_VARIABLE_NAME = "Left_Click_Button_Canceled_Variable",
                        RIGHT_CLICK_BUTTON_PERFORMED_VARIABLE_NAME = "Right_Click_Button_Performed_Variable",
                        RIGHT_CLICK_BUTTON_CANCELED_VARIABLE_NAME = "Right_Click_Button_Canceled_Variable",
                        MOUSE_DELTA_POSITION_VARIABLE_NAME = "Mouse_Delta_Position_Variable",
                        MOUSE_SCREEN_POSITION_VARIABLE_NAME = "Mouse_Screen_Position_Variable",
                        MOUSE_WORLD_POSITION_VARIABLE_NAME = "Mouse_World_Position_Variable",
                        //Game events
                        LEFT_CLICK_BUTTON_PERFORMED_GAME_EVENT_NAME = "Left_Click_Button_Performed_Event",
                        LEFT_CLICK_BUTTON_CANCELED_GAME_EVENT_NAME = "Left_Click_Button_Canceled_Event",
                        RIGHT_CLICK_BUTTON_PERFORMED_GAME_EVENT_NAME = "Right_Click_Button_Performed_Event",
                        RIGHT_CLICK_BUTTON_CANCELED_GAME_EVENT_NAME = "Right_Click_Button_Canceled_Event";
                    }
                }

                //Nested class, used to store scriptable object keyboard input information
                public class KeyboardInputScriptableObjectsNaming
                {
                    //Variables
                    public readonly string DEFAULT_KEYBOARD_INPUT_PATH = "Assets/Resources/MECS/Input/PC/Keyboard",
                    DEFAULT_KEYBOARD_INPUT_FOLDER_NAME = "Keyboard",
                    DEFAULT_KEYBOARD_INPUT_SHORT_PATH = "MECS/Input/PC/Keyboard";
                    public readonly KeyboardInputAssetsScriptableObjectsNaming keyboardInputAssetsScriptableObjectsNaming = new();

                    //Nested class, used to share scriptable objects assets keyboard input information
                    public class KeyboardInputAssetsScriptableObjectsNaming
                    {
                        //Variables
                        public readonly string A_BUTTON_PERFORMED_VARIABLE_NAME = "A_Button_Performed_Variable",
                            A_BUTTON_CANCELED_VARIABLE_NAME = "A_Button_Canceled_Variable",
                            D_BUTTON_PERFORMED_VARIABLE_NAME = "D_Button_Performed_Variable",
                            D_BUTTON_CANCELED_VARIABLE_NAME = "D_Button_Canceled_Variable",
                            S_BUTTON_PERFORMED_VARIABLE_NAME = "S_Button_Performed_Variable",
                            S_BUTTON_CANCELED_VARIABLE_NAME = "S_Button_Canceled_Variable",
                            SPACE_BUTTON_PERFORMED_VARIABLE_NAME = "Space_Button_Performed_Variable",
                            SPACE_BUTTON_CANCELED_VARIABLE_NAME = "Space_Button_Canceled_Variable",
                            W_BUTTON_PERFORMED_VARIABLE_NAME = "W_Button_Performed_Variable",
                            W_BUTTON_CANCELED_VARIABLE_NAME = "W_Button_Canceled_Variable",
                            //Game events
                            A_BUTTON_PERFORMED_GAME_EVENT_NAME = "A_Button_Performed_Event",
                            A_BUTTON_CANCELED_GAME_EVENT_NAME = "A_Button_Canceled_Event",
                            D_BUTTON_PERFORMED_GAME_EVENT_NAME = "D_Button_Performed_Event",
                            D_BUTTON_CANCELED_GAME_EVENT_NAME = "D_Button_Canceled_Event",
                            S_BUTTON_PERFORMED_GAME_EVENT_NAME = "S_Button_Performed_Event",
                            S_BUTTON_CANCELED_GAME_EVENT_NAME = "S_Button_Canceled_Event",
                            SPACE_BUTTON_PERFORMED_GAME_EVENT_NAME = "Space_Button_Performed_Event",
                            SPACE_BUTTON_CANCELED_GAME_EVENT_NAME = "Space_Button_Canceled_Event",
                            W_BUTTON_PERFORMED_GAME_EVENT_NAME = "W_Button_Performed_Event",
                            W_BUTTON_CANCELED_GAME_EVENT_NAME = "W_Button_Canceled_Event";
                    }
                }
            }
        }
    }
}